name: anti_hook_vpn
description: "Flutter plugin to detect VPN, Proxy, and Frida hooking on Android & iOS. Protect your app from runtime attack tools."
version: 1.0.3
homepage: https://github.com/hainguyen-ar1/anti_hook_vpn
repository: https://github.com/hainguyen-ar1/anti_hook_vpn
issue_tracker: https://github.com/hainguyen-ar1/anti_hook_vpn/issues

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.anti_hook_vpn
        pluginClass: AntiHookVpnPlugin
      ios:
        pluginClass: AntiHookVpnPlugin
