name: anti_hook_vpn
description: "Flutter plugin phát hiện VPN, Proxy và Frida hook trên Android và iOS. Bảo vệ ứng dụng khỏi các công cụ tấn công runtime."
version: 1.0.0
homepage: https://github.com/hainguyen-ar1/anti_hook_vpn
repository: https://github.com/hainguyen-ar1/anti_hook_vpn
issue_tracker: https://github.com/hainguyen-ar1/anti_hook_vpn/issues

environment:
  sdk: ^3.9.0
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.example.anti_hook_vpn
        pluginClass: AntiHookVpnPlugin
      ios:
        pluginClass: AntiHookVpnPlugin
